spring:
  thymeleaf:
    #å»é™¤thymeleafçš„htmlä¸¥æ ¼æ ¡éªŒ
    mode: LEGACYHTML5
    #è®¾å®šthymeleafæ–‡ä»¶è·¯å¾„ï¼Œé»˜è®¤ä¸ºsrc/main/resources/templates
#    prefix: classpath:/templates/
    suffix: .htm
    #æ˜¯å¦å¼€å¯æ¨¡æ¿ç¼“å­˜ï¼Œé»˜è®¤trueï¼Œå»ºè®®åœ¨å¼€å‘æ—¶å…³é—­ç¼“å­˜,ä¸ç„¶æ²¡æ³•çœ‹åˆ°å®æ—¶é¡µé¢ï¼Œä¹Ÿå°±æ˜¯ä¿®æ”¹äº†htmlåä¸ç”¨é‡å¯ï¼Œåˆ·æ–°é¡µé¢å°±èƒ½çœ‹åˆ°æ•ˆæœï¼Œä¿®æ”¹å®Œhtmlåä¸€å®šè¦ctrl+f9é‡æ–°buildä¸€ä¸‹ã€‚
    cache: false
    #æ¨¡æ¿ç¼–ç 
    encoding: UTF-8
  application:
    name=siyubao: siyubao

logging:
  config: classpath:logback-local.xml

deepseek:
  api:
    url: "http://127.0.0.1:11434/api/chat"
    model: "deepseek-r1:8b"

siyubao:
  url: https://aih5.lm12301.com/h1/shortcode/getorderinfo/

##è¿™æ˜¯å°†åˆ«äººçš„ç§åŸŸå®èŠå¤©æˆªå›¾æ›¿æ¢æˆè‡ªå·±çš„æŠ–éŸ³å·åç§°å’Œå›¾åƒ
tihuan:
  enshi:
    name: æ©æ–½ç™¾æ™“é€š
    imgPic:  https://p26.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-i-0813c001_owEAQCKfa5HIKfA9IRtnlAFPgABD6FgAAG0ErC.jpeg?from=4010531038
  cq:
    name: å…‰æ˜ç»è¥éƒ¨
    imgPic:  ./avatar/dytxcq.jpg
  sc:
    name: æ¯›æ¯›çˆ±æ—…ç©
    imgPic: ./avatar/dytxsc.jpg
  xj:
    name: è‰è‰çˆ±æ—…ç©
    imgPic: ./avatar/dytxxj.jpg
  bj:
    name: é”¦è¡Œåœ¨åŒ—äº¬
    imgPic: ./avatar/dytxbj.jpg
  lm:
    name: å†…è’™æœ¬åœ°é€š
    imgPic: ./avatar/dytxlm.jpg

##è¿™æ˜¯ç”¨deepseekç”Ÿæˆè‡ªå·±çš„å‡èŠå¤©æˆªå›¾
xianlu:
#  name: "æ©æ–½"
#  englishName: enshi
#  jitianjiwan: "4å¤©"
#  welcomword: "ä½ å¥½ï¼Œæ¬¢è¿æ¥${xianlu.name}æ—…æ¸¸ï¼ ç›®å‰${xianlu.name}æ—…æ¸¸é™æ—¶ç‰¹æƒ ä¼˜æƒ å¤šå¤šï¼Œæ‚¨è¿™è¾¹å¤§æ¦‚å‡ ä¸ªäººï¼Œä»€ä¹ˆæ—¶å€™å‡ºè¡Œå‘¢ï¼Ÿå¯ä»¥ç•™ä¸ªè”ç³»æ–¹å¼ï¼Œç»™ä½ å‘è¡Œç¨‹æŠ¥ä»·å‚è€ƒä¸‹ï¼"
#  finalword: "æ”¶åˆ°ï¼Œç¨åæ‚¨çš„ä¸“å±ç®¡å®¶ä¼šå’Œæ‚¨å¯¹æ¥"
#  questionFile: enshi.txt
  name: "æ–°ç–†"
  englishName: xj
  jitianjiwan: "8å¤©"
  welcomword: "ä½ å¥½ï¼Œæ¬¢è¿æ¥${xianlu.name}æ—…æ¸¸ï¼ ç›®å‰${xianlu.name}æ—…æ¸¸é™æ—¶ç‰¹æƒ ä¼˜æƒ å¤šå¤šï¼Œæ‚¨è¿™è¾¹å¤§æ¦‚å‡ ä¸ªäººï¼Œä»€ä¹ˆæ—¶å€™å‡ºè¡Œå‘¢ï¼Ÿå¯ä»¥ç•™ä¸ªè”ç³»æ–¹å¼ï¼Œç»™ä½ å‘è¡Œç¨‹æŠ¥ä»·å‚è€ƒä¸‹ï¼"
  finalword: "ğŸ‘ŒğŸ‘Œæ”¶åˆ°ï¼Œç®¡å®¶ç°åœ¨æ·»åŠ æ‚¨
               è¯¦ç»†æ²Ÿé€šè¡Œç¨‹ğŸ“‘å’ŒæŠ¥ä»·ğŸ’°

               åˆšå¥½å…¬å¸ç°åœ¨æœ‰ä¼˜æƒ æ´»åŠ¨ï¼
               åˆ°æ—¶å€™å¯ä»¥å¸®æ‚¨ç”³è¯·ä¼˜æƒ å“¦ï¼

               æ‚¨æ³¨æ„ä¸‹å¥½å‹ç”³è¯·ï¼ï¼"
  questionFile: xj.txt
